version: "3.8"
services:
  condlanedet:
    #image: nvcr.io/nvidia/tensorflow:23.03-tf1-py3
    image: condlanedet-dev:0.1
    command: bash
    shm_size: '2gb'  # 增加共享内存
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    devices:
      - "/dev/video0:/dev/video0:mwr"
    volumes:
      - /home/zyb/conditional-lane-detection:/app
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    network_mode: host
    environment:
      - DISPLAY=${DISPLAY}
      - XDG_RUNTIME_DIR=${XDG_RUNTIME_DIR}
    privileged: true
    ipc: host
    ulimits:
      memlock:
        soft: -1
        hard: -1
      stack:
        soft: 67108864
        hard: 67108864
    stdin_open: true   # equivalent to -i
    tty: true          # equivalent to -t

